targets:
  $default:
    builders:
      jsoninflater|json_inflater:
        enabled: true
      jsoninflater|json_gather:
        enabled: true

builders:
  json_inflater:
    import: "package:jsoninflater/jsonInflater.dart"
    builder_factories: ["jsonInflaterBuilder"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache
    runs_before: ['jsoninflater|json_gather']

  json_gather:
    import: "package:jsoninflater/jsonGather.dart"
    builder_factories: ["jsonGatherBuilder"]
    build_extensions: {".dart": [".internal.dart"]}
    auto_apply: root_package
    build_to: source