author: ejin66
homepage: https://github.com/ejin66/JsonInflater
name: jsoninflater
description: Json decoding supports generics
version: 0.2.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  json_serializable: ^2.0.0
  json_annotation: ^2.0.0
  build_runner: ^1.0.0
  
